import "dotenv/config"
import { prisma } from "../lib/db"
import { getTrainingBlock, invalidateTrainingCache } from "../lib/ai-training"

export const MASTER_RULES = [
  {
    title: "Lead with Attractive Character",
    scope: "global",
    surface: "EMAIL" as const,
    sourceRef: "DotCom Secrets by Russell Brunson — Pages 1–4, 46–51",
    instruction: "Start every cold communication with a relatable, specific story or persona that mirrors the prospect's exact pain and journey, then transition to your offer.",
    goodExample: '“Hey [Name], a few years ago I was in your seat—running an agency burning out on client calls, unable to scale past $20k/month. That\'s when I realized the problem wasn\'t the work, it was the offer. Let me show you how we flipped it.”',
    badExample: '“Hi [Name], we are a full-service growth marketing agency. We offer SEO, PPC, and social media management. Would you be interested in a free consultation?”',
  },
  {
    title: "Agitate, Then Reveal Secret Formula",
    scope: "global",
    surface: "ALL" as const,
    sourceRef: "DotCom Secrets by Russell Brunson — Pages 1–4",
    instruction: "Structure every pitch by first highlighting the specific pain, then explaining your unique mechanism, and finally showing the desired outcome.",
    goodExample: '“The reason your ad costs are climbing isn\'t the creative—it\'s the landing page. Our \'Value Gap\' mechanism inserts a bridge offer that lifts conversion 2x while lowering CAC. Your pipeline finally becomes predictable.”',
    badExample: '“We offer landing page design, A/B testing, and CRO. We can help you get more conversions.”',
  },
  {
    title: "Lead with Dream Client Outcome",
    scope: "global",
    surface: "EMAIL" as const,
    sourceRef: "DotCom Secrets by Russell Brunson — Pages 1–4, 18–19",
    instruction: "In your outreach, explicitly identify the dream client's pain point and position your solution as the bridge to their desired outcome.",
    goodExample: '“Your biggest holdback isn\'t more traffic—it\'s that you\'re leaving $50k on the table after the initial sale. We build a value ladder that turns one-time clients into $10k backend buyers.”',
    badExample: '“We can help you get more leads.”',
  },
  {
    title: "Map Full Funnel, Not Surface",
    scope: "global",
    surface: "ADVISOR" as const,
    sourceRef: "DotCom Secrets by Russell Brunson — Pages 15–17, 84–85",
    instruction: "When researching or fixing a client's campaign, identify not just the landing page but the entire invisible offer sequence (lead magnet, tripwire, upsell) that happens after the first click.",
    goodExample: '“I reviewed your funnel skeleton. You have a lead magnet and a core offer, but no tripwire. Here\'s what Dropbox would do: free report → $7 tripwire → $47 core → $197 upsell. We need to plug that gap.”',
    badExample: '“Your landing page looks good; we just need to drive more traffic.”',
  },
  {
    title: "Pre-frame Cold Traffic with Education",
    scope: "global",
    surface: "EMAIL" as const,
    sourceRef: "DotCom Secrets by Russell Brunson — Pages 94–98",
    instruction: "For cold traffic, add an educational pre-frame page or section that defines unfamiliar terms and connects them to the prospect's pain before presenting the offer.",
    goodExample: '“Hey [Name], before I pitch you, you need to know the difference between \'leads\' and \'qualified buyers.\' A lead is just a name. A qualified buyer is someone who\'s already proven they\'ll pay. Here\'s how we separate the two.”',
    badExample: '“Hi [Name], check out our new LinkedIn Ads package. It\'s perfect for you.”',
  },
  {
    title: "Use Squeeze Pages for Email Only",
    scope: "global",
    surface: "ADVISOR" as const,
    sourceRef: "DotCom Secrets by Russell Brunson — Pages 40–45",
    instruction: "When running paid traffic, route it to a distraction-free squeeze page with only one conversion goal: email capture, or exit. No secondary links or offers.",
    goodExample: '“Your landing page has 3 CTAs: \'Book a Call\', \'Download the PDF\', and \'Learn More\'. Let\'s strip it to one: \'Get the Free Guide\'. Every visitor becomes an email lead before they see any other offer.”',
    badExample: '“Add a button for \'Schedule Demo\' next to your email capture form to give people options.”',
  },
  {
    title: "Build Value Ladder Sequence",
    scope: "global",
    surface: "PROPOSAL" as const,
    sourceRef: "DotCom Secrets by Russell Brunson — Pages 23–33",
    instruction: "Always present a low-cost, low-risk first offer before pitching any high-ticket service, to establish value and build trust.",
    goodExample: '“Don\'t sell your $10k consulting package immediately. Start with a $97 offer to \'solve one bottleneck\'. Once they buy that, they\'re 10x more likely to buy the $10k retainer.”',
    badExample: '“Let\'s bid on this high-intent keyword and hope they buy the full package on the first visit.”',
  },
  {
    title: "Offer Tripwire to Qualify Buyers",
    scope: "global",
    surface: "PROPOSAL" as const,
    sourceRef: "DotCom Secrets by Russell Brunson — Pages 99–111",
    instruction: "After a prospect opts in, immediately present a low-priced, high-value \'tripwire\' offer (e.g., $7) to separate buyers from subscribers and activate your email follow-up sequence.",
    goodExample: '“After the \'free guide\' opt-in, redirect to a \'$7 One-Click Upsell\' page. This instantly tells you who\'s a buyer and who\'s just a lead.”',
    badExample: '“Just collect the email and hope they buy later from your newsletter.”',
  },
  {
    title: "Upsell the Logical Next Step",
    scope: "global",
    surface: "PROPOSAL" as const,
    sourceRef: "DotCom Secrets by Russell Brunson — Pages 122–123",
    instruction: "After any front-end purchase, offer a product that logically follows the buyer's core goal—never an unrelated item—and frame it as a way to get faster results.",
    goodExample: '“After they buy \'SEO Basics\', upsell \'SEO Tools $20/mo\' or \'Advanced Link Building Guide\'. Tell them: \'If you want to rank in 3 weeks instead of 3 months, this is your next step.\'”',
    badExample: '“Offer them a discount on a different product like web design after they buy SEO training.”',
  },
  {
    title: "Stack Value Before Anchoring Price",
    scope: "global",
    surface: "PROPOSAL" as const,
    sourceRef: "DotCom Secrets by Russell Brunson — Pages 130–149, 172–176",
    instruction: "Before revealing the cost, stack every deliverable in a list and quantify it (e.g., \'That\'s a $5,000 value\'), then anchor the price against that total value, not the final price.",
    goodExample: '“This package includes: 1) Strategy Session ($2000), 2) Full Funnel Audit ($1500), 3) 3 Months Support ($1000). Total value: $5000. Your investment is just $2000.”',
    badExample: '“Our consulting package is $2,000. It includes a strategy session and some support.”',
  },
  {
    title: "Use Emotional 'If All' Close",
    scope: "global",
    surface: "REPLY" as const,
    sourceRef: "DotCom Secrets by Russell Brunson — Pages 144–149, 164–165",
    instruction: "After presenting the price, immediately close with an \'If all...\' statement that ties the offer to a deep desire or relief from pain.",
    goodExample: '“\'So, if all this gets you 10 more qualified sales calls a month, and you close even 20%, that\'s 2 new clients—which pays for itself 10x over... would that be worth it?\'”',
    badExample: '“So, this is the price. Do you want it or not?”',
  },
  {
    title: "Name the Real Objection",
    scope: "global",
    surface: "REPLY" as const,
    sourceRef: "DotCom Secrets by Russell Brunson — Pages 64–69",
    instruction: "When a prospect dismisses your value or says \'nothing\' is wrong, directly call out the awkwardness or hidden objection and ask them to define what would happen if they did nothing.",
    goodExample: '“\'It sounds like you\'re saying \'nothing\' is broken, but you called me. If you did nothing for the next 6 months, what\'s the cost of that? Let\'s put a dollar figure on the problem you\'re ignoring.\'”',
    badExample: '“Are you sure? Our solution is really great.”',
  },
  {
    title: "Mirror Their Glare",
    scope: "global",
    surface: "REPLY" as const,
    sourceRef: "DotCom Secrets by Russell Brunson — Pages 64–69",
    instruction: "If the prospect repeats the same skeptical phrase, mirror it back exactly to force them to explain the real objection.",
    goodExample: '“Prospect: \'We just don\'t have budget for this.\' You: \'You don\'t have budget for this? So if I showed you a way to 2x your pipeline, would budget magically appear?\'”',
    badExample: '“Is it a cost issue? We can find a cheaper package.”',
  },
  {
    title: "Replace Excuse with Skill Gap",
    scope: "global",
    surface: "REPLY" as const,
    sourceRef: "DotCom Secrets by Russell Brunson — Pages 182–189",
    instruction: "When a prospect says they lack time or money, restate their excuse as a missing skill or knowledge gap and ask a question that makes them admit they'd act if they had that knowledge.",
    goodExample: '“Prospect: \'We don\'t have time to set up a funnel.\' You: \'So if you had a done-for-you system that required 30 min/month, you\'d say yes? The issue isn\'t time, it\'s that you haven\'t seen a simple enough process.\'”',
    badExample: '“Sure, let\'s schedule it for when you have more time.”',
  },
  {
    title: "Probe Financial Capacity Early",
    scope: "global",
    surface: "REPLY" as const,
    sourceRef: "DotCom Secrets by Russell Brunson — Pages 190–192",
    instruction: "When a prospect shows interest, ask about their credit and available capital using a concrete numbers-based scenario to gauge if they can buy now.",
    goodExample: '“\'To make this work, you\'ll need about $2k. Is that capital available in your business today, or would you need to use a credit card?\'”',
    badExample: '“Just ask them \'Do you have budget for this?\'.”',
  },
  {
    title: "Ask Why, Then Stay Silent",
    scope: "global",
    surface: "REPLY" as const,
    sourceRef: "DotCom Secrets by Russell Brunson — Pages 184–189",
    instruction: "After a prospect agrees they'd be successful with your help, ask \'Why?\' or \'How come?\' to prompt deeper motivations, then stop talking and actively listen for at least 3 seconds.",
    goodExample: '“Prospect: \'Yes, I think we could work together.\' You: \'Why?\' (Then wait silently for them to reveal their true desire).”',
    badExample: '“Great! Let\'s get the paperwork signed.”',
  },
  {
    title: "Use Third-Party Bridge",
    scope: "global",
    surface: "ADVISOR" as const,
    sourceRef: "DotCom Secrets by Russell Brunson — Pages 94–105",
    instruction: "When driving traffic, use a trusted partner's testimonial, video, or recommendation as a pre-frame to inherit their credibility before linking to your offer.",
    goodExample: '“We need to find a micro-influencer in your niche to review your product on their YouTube channel, and then drive their audience to a \'special link\' where you can pitch them as a trusted source.”',
    badExample: '“Let\'s boost a post on Facebook and see what happens.”',
  },
  {
    title: "Create Open Loops",
    scope: "global",
    surface: "EMAIL" as const,
    sourceRef: "DotCom Secrets by Russell Brunson — Pages 52–54",
    instruction: "Open a curiosity gap in one email and explicitly promise to close it in the next email to drive sequential opens.",
    goodExample: '“Email 1 subject: \'The #1 mistake you\'re making with leads.\' Email 1 end: \'I\'ll tell you the exact fix tomorrow.\' Email 2 subject: \'The fix (it\'s not what you think).\'”',
    badExample: '“Email 1: \'Here are 10 ways to get more leads.\' Email 2: \'Here are 10 more ways.\'”',
  },
  {
    title: "Start at High Drama",
    scope: "global",
    surface: "ALL" as const,
    sourceRef: "DotCom Secrets by Russell Brunson — Pages 52–54, 136–139",
    instruction: "When telling a story in sales copy or email, start at the moment of highest tension, then backtrack to explain how you got there.",
    goodExample: '“I almost lost my biggest client last month. We\'d been with them 3 years, and they were ready to leave. Here\'s the story of how I saved it...”',
    badExample: '“Let me tell you about last month. I started my day normally and then I got an email...”',
  },
  {
    title: "Disqualify Non-Dream Clients",
    scope: "global",
    surface: "REPLY" as const,
    sourceRef: "DotCom Secrets by Russell Brunson — Pages 75–80",
    instruction: "When a prospect dismisses your value or claims they know everything, politely but firmly disqualify them from working with you to increase your status and filter out toxic leads.",
    goodExample: '“I appreciate your confidence. Based on this conversation, it sounds like you\'re looking for a vendor, not a partner. We only work with founders who are ready to invest 1 hour a week in this. It doesn\'t sound like that\'s you. I\'ll stop here.”',
    badExample: '“No, we\'re really good! Can you give us another chance?”',
  },
  {
    title: "Future-Pace the Ownership",
    scope: "global",
    surface: "PROPOSAL" as const,
    sourceRef: "DotCom Secrets by Russell Brunson — Pages 177–193",
    instruction: "When presenting a pitch, lead the prospect through a first-person visualization of completing the exact process before you reveal the offer.",
    goodExample: '“Imagine it\'s 6 months from now. You\'re sitting in your office, you check your dashboard, and you see 20 new qualified leads waiting. You didn\'t have to build anything—it\'s just working. How does that feel?”',
    badExample: '“This product will automate your marketing.”',
  },
  {
    title: "Match Message to Traffic Temperature",
    scope: "global",
    surface: "ALL" as const,
    sourceRef: "DotCom Secrets by Russell Brunson — Pages 94–101",
    instruction: "Write differently for cold, warm, and hot traffic: for cold, educate and pre-frame; for warm, be direct; for hot, go straight to the offer with urgency.",
    goodExample: '“Cold: \'Do you know what a \'lead magnet\' is? It\'s a freebie to get emails.\' Warm: \'Now here\'s the exact $7 offer to bridge the gap.\' Hot: \'You\'re ready. Buy it now.\'”',
    badExample: '“Writing the same sales pitch for a cold Facebook ad and a warm email list.”',
  },
  {
    title: "Sell the Outcome, Not the Effort",
    scope: "global",
    surface: "ALL" as const,
    sourceRef: "DotCom Secrets by Russell Brunson — Pages 18, 88",
    instruction: "Lead every email, proposal, and reply with the specific financial or operational outcome the prospect gets — never the features, process, or effort that goes into your product.",
    goodExample: '“Our onboarding system gets you from signed contract to active user in 4 days, so you stop paying for your old redundant tool by the end of the month.”',
    badExample: '“Our platform has an intuitive interface with a customizable dashboard and gives you access to our 247 support team.”',
  },
  {
    title: "Sell to One Person Only",
    scope: "global",
    surface: "EMAIL" as const,
    sourceRef: "DotCom Secrets by Russell Brunson — Pages 14-15, 16",
    instruction: "In every campaign, email, and proposal, name the specific niche customer and their exact situation in the headline and opening line so they feel you've read their private memo.",
    goodExample: '“For managing partners at 20-person manufacturing firms losing 3 bids a month to same-day quote requests...”',
    badExample: '“Are you struggling to grow your small business? Our solutions help you scale faster.”',
  },
  {
    title: "Lead with Pain, Proof, Plan",
    scope: "global",
    surface: "EMAIL" as const,
    sourceRef: "DotCom Secrets by Russell Brunson — Pages 1-4, 5-7",
    instruction: "Open with a problem the buyer already feels, then social proof, then a one-sentence plan. Do not open with your story, your platform, or your award.",
    goodExample: '“Your inbound leads are closing at 12% because your SDRs use the same template for VC-backed startups and local services firms. The top 5 execs we audited last month switched to a diagnostic-based script and hit 24% — want to see the structure?”',
    badExample: '“Hi! We\'re Acme Agency, a full-service growth partner using data-driven methods to help brands like yours scale. Check out our case studies below.”',
  },
  {
    title: "Anchor with a Contrast Metric",
    scope: "global",
    surface: "REPLY" as const,
    sourceRef: "DotCom Secrets by Russell Brunson — Pages 68-71",
    instruction: "When a prospect asks about price or ROI, instantly counter by anchoring to a hard number — the cost of inaction or a specific leverage point (leads, conversion rate, margin) — before quoting your fee.",
    goodExample: '“Sure, the retainer is $6k/mo. But that\'s 0.5% of the revenue gap you identified last call — and the first 10% improvement in your existing conversion rate pays for the entire year. Shall we go deeper?”',
    badExample: '“Our pricing is actually pretty standard for the industry. We\'re around the $5k-$8k mark depending on scope — let me send you the proposal.”',
  },
  {
    title: "Package an Irresistible Offer",
    scope: "global",
    surface: "PROPOSAL" as const,
    sourceRef: "DotCom Secrets by Russell Brunson — Pages 14-15, 19-20",
    instruction: "In the proposal, structure offers as the main outcome plus a stacked set of high-perceived-value bonuses that cost you little but look expensive; always list the total value, then show the discounted total.",
    goodExample: '“For $15k you get the full email engine build and launch, plus the 6-week implementation sprint ($4k), the QA fail-safe audit ($2k), and the \'don\'t launch to crickets\' guaranteed reply test ($1k). Total value $22k, your investment only $15k.”',
    badExample: '“Our service includes email marketing, some landing pages, and a dashboard. We usually charge around $15k depending on requirements.”',
  },
  {
    title: "Include a Bold Risk Reversal",
    scope: "global",
    surface: "PROPOSAL" as const,
    sourceRef: "DotCom Secrets by Russell Brunson — Pages 58-60",
    instruction: "Every proposal must state a concrete, measurable guarantee that shifts the financial risk of non-performance onto you — not a polite \'we\'ll make it right\' promise.",
    goodExample: '“If your open rates don\'t double in the first 60 days after we launch, we will continue to optimize the flows free for another 60 days until they do — no questions asked.”',
    badExample: '“We\'re committed to your success and will do everything we can to make this relationship work. We value long-term partnerships.”',
  },
  {
    title: "Frame Pricing as Two Tiers",
    scope: "global",
    surface: "PROPOSAL" as const,
    sourceRef: "DotCom Secrets by Russell Brunson — Pages 58-60",
    instruction: "Always present exactly two to three price tiers (standard, premium) side-by-side, framing the premium tier as roughly double the cost for more than double the value — never present a single price or four confusing options.",
    goodExample: '“Option A: Standard — $10k flat with the monthly retainers. Option B: Premium — $18k where we also assign a dedicated growth analyst (value $8k) and onboard success manager (value $3k) — you get that plus everything in Standard.”',
    badExample: '“Our pricing is flexible and final quotes depend on a few factors. We have different tiers we can explore together — let me know what your budget range is.”',
  },
  {
    title: "Treat Tech as a Team Member",
    scope: "global",
    surface: "ADVISOR" as const,
    sourceRef: "DotCom Secrets by Russell Brunson — Pages 63-66",
    instruction: "When deciding to use a new tool or software in your process, define its specific job, and outline the key performance indicator (KPI) it must hit within 60 days; if it misses the metric, remove it from the workflow.",
    goodExample: '“We will deploy the cold-email sequencer for the next 30 days with the red flag logic. If it doesn\'t help our SDR book 2 meetings per day by day 30, we will disable the automation and switch to manual follow-up.”',
    badExample: '“Let\'s try this new CRM feature that does the follow-ups for us — it should save some time. Let’s see how it goes.”',
  },
  {
    title: "Work Backwards from Front-End ROI",
    scope: "global",
    surface: "ADVISOR" as const,
    sourceRef: "DotCom Secrets by Russell Brunson — Pages 27-32, 37-41",
    instruction: "When building lead-gen campaigns, evaluate them by immediate revenue/lead cost first (front-end ROI); if not profitable, build a deliberate upsell or repeat-purchase path into the funnel to make the economics work on the back-end.",
    goodExample: '“The $2k lead gen retainer will produce 40 SQLs. It fails front-end ROI, but with the auto-proposal upsell path, we can close 8% at $10k ACV → that makes the campaign profitable by week 4, not month 6.”',
    badExample: '“We\'ll set up Facebook ads to drive traffic. We\'ll worry about SEO and conversion rate optimization later once we start collecting data and the brand builds up.”',
  },
  {
    title: "Write as an Insider, Not a Sales Rep",
    scope: "global",
    surface: "EMAIL" as const,
    sourceRef: "DotCom Secrets by Russell Brunson — Pages 29-30, 33-34",
    instruction: "In every message, use the prospect's internal jargon, describe their day-to-day frustrations like you've sat in their seat, and ban generic corporate phrases like \'synergy\' or \'industry-leading\'.",
    goodExample: '“The CFO has stopped caring about the product price. He cares about the asset turn ratio — you\'re currently sitting at 1.2 with 34% excess inventory. We\'ve shipped a fix for this exact bottleneck at 3 other wholesale operations this quarter.”',
    badExample: '“Our solutions will optimize your inventory to ensure maximum efficiency across your entire supply chain.”',
  },
  {
    title: "Force a Follow-Up Transformation",
    scope: "global",
    surface: "EMAIL" as const,
    sourceRef: "DotCom Secrets by Russell Brunson — Pages 53-54, 55-57",
    instruction: "Never end an initial email with just a question — end it with a new, previously unstated value insight or mini-reveal about their process, so that even if they don't respond now, they save the email for future reference.",
    goodExample: '“Even if we don\'t speak now, the one thing I\'d bake into your new onboarding flow is the \'activation survey\' before their first call — it alone drops churn by 18% in the first quarter, I’ll send the template over for when you\'re ready.”',
    badExample: '“Let me know if you are open to a quick call to discuss this further.”',
  },
  {
    title: "Capitalize on Prospects' Trigger Events",
    scope: "global",
    surface: "REPLY" as const,
    sourceRef: "DotCom Secrets by Russell Brunson — Pages 77-78",
    instruction: "When a prospect goes quiet or is lukewarm, ask a direct question about a specific life, hiring, or business event that commonly spikes demand for your service, and align your offer to that specific moment.",
    goodExample: '“Have you had any turnover in your revenue operations team this month? When we\'ve seen that, the new hire almost always drops the email ball — we replaced the mess with a 3-day migration and they saw a 40% lift in replies the following week.”',
    badExample: '“Just checking in! Wondering if you had any decision updates or if anything changed on your end?”',
  },
  {
    title: "Respond to Interest with a Question",
    scope: "global",
    surface: "REPLY" as const,
    sourceRef: "DotCom Secrets by Russell Brunson — Pages 55-57",
    instruction: "When a lead replies \'yes\' or asks for details, do not fire off pricing or a link — immediately ask a strategic qualification question about their process, deadline, or criteria to keep the power dynamic balanced and unlock budget.",
    goodExample: '“That\'s great! So we can build the right scope — when the CFO rejects a proposal now, is it a price objection, or a fear that the ROI isn\'t tangible enough to report to the board?”',
    badExample: '“Sounds good! I\'m attaching the deck to this email, along with the pricing sheet. Let me know what you think!”',
  },
  {
    title: "Name the Elephant on the Call",
    scope: "global",
    surface: "REPLY" as const,
    sourceRef: "DotCom Secrets by Russell Brunson — Pages 21-21, 61-62",
    instruction: "On any sales call or reply, the startup should proactively mention the #1 perceived risk or objection they haven't brought up yet, and attack it before they say it — never wait to resolve it reactively.",
    goodExample: '“It\'s normal to worry that outsourcing your growth to us means losing day-to-day visibility. That\'s why we co-manage the dashboard with your VPM and cap the first sprint at 30 days, so you can see the pipeline gains before the full contract kicks in.”',
    badExample: '“We have a strong track record of closing B2B deals, but of course every client environment is unique. We\'ll keep you in the loop as always.”',
  },
  {
    title: "Pre-Communicate Referral Expectations",
    scope: "global",
    surface: "ALL" as const,
    sourceRef: "DotCom Secrets by Russell Brunson — Pages 76-77",
    instruction: "During the sales and onboarding phase, specifically state that part of your model includes an expectation of client referrals (e.g., 3 per client), so future requests are an obligation, not a favor.",
    goodExample: '“Before we start, I should share — my team is referral-based. So as part of our 90-day engagement, I’ll be asking you for the names of 3 colleagues who face the same specific challenges, so we can replicate the win. Fair?”',
    badExample: '“If you know anyone who needs our services, we\'d love it if you sent them our way.”',
  },
  {
    title: "Position as a Specialist",
    scope: "global",
    surface: "PROPOSAL" as const,
    sourceRef: "DotCom Secrets by Russell Brunson — Pages 16-16, 19-20",
    instruction: "In the first two lines of any proposal, lead with a measurable outcome or niche you're dominant in (\'For SaaS companies with $5-10M ARR\') before saying your company name.",
    goodExample: '“For PE-backed industrial distributors doing $20M+ revenue, we halve the sales cycle by re-kitting the CRM to the new entity structure. Our proposal is below.”',
    badExample: '“Hi, this is SDR1 from Acme. We help mid-size companies scale their revenue operations. Here\'s our proposal.”',
  },
  {
    title: "Build a Curiosity Package",
    scope: "global",
    surface: "EMAIL" as const,
    sourceRef: "DotCom Secrets by Russell Brunson — Pages 47-49, 50-52",
    instruction: "When a prospect has shown interest but hasn't bought, mail a physical package containing a relevant book or a bespoke \'insight report\' into their process — never send email alone in the first 3 follow-ups.",
    goodExample: '“I mailed you a copy of \'The Ultimate Split Test Guide\' and a hand-annotated audit of your current landing page conversion path — page 14 has the specific element that\'s leaking leads. You won’t find this template online.”',
    badExample: '“Since you\'re not available for a call, I\'ll love to send you over our company brochure and generic \'best practices\' one-pager.”',
  },
  {
    title: "Force 'Act Now' Iteration Loop",
    scope: "global",
    surface: "ADVISOR" as const,
    sourceRef: "DotCom Secrets by Russell Brunson — Pages 81-85",
    instruction: "When building any sales flow or asset, ship a workable version to a small seed audience in 24 hours, measure response against baseline, and then iterate twice — never wait until a campaign is perfect to launch.",
    goodExample: '“Let\'s launch the revised cold email sequence to 15 prospects by noon with the new niche headline — if we don\'t get 2 replies by 5:00, we abort and re-write the first 3 lines tomorrow.”',
    badExample: '“Let me have the design team polish the custom landing page for this new segment, and then we’ll revisit the entire outreach strategy next month.”',
  },
  {
    title: "Convert Metrics into Transactions",
    scope: "global",
    surface: "ADVISOR" as const,
    sourceRef: "DotCom Secrets by Russell Brunson — Pages 68-71, 81-85",
    instruction: "Track exactly — and state in every reporting email or touchpoint — the number of leads, conversion rate, and average transaction value; then tie your fee to a specific percentage improvement in all three levers.",
    goodExample: '“Last month you had 1500 leads, 8% conversion, and $750 ACV. With the new flow we deployed, we\'re targeting 1800 leads, 12% conversion, and $850 ACV — that\'s an extra $238k in revenue quarterly. We measure our own position against that growth.”',
    badExample: '“Metrics have improved significantly. We\'re seeing strong progress across the board and page traffic is up. Happy to go over the details with you.”',
  },
  {
    title: "Display Trust Signals in Every Message",
    scope: "global",
    surface: "ALL" as const,
    sourceRef: "DotCom Secrets by Russell Brunson — Pages 58-60",
    instruction: "In your email signature, proposal cover, and every reply, include a physical street address, a professional domain email (no gmail), and a landline or non-mobile phone number — never rely on logo or words to build trust.",
    goodExample: '“Margot, feel free to reach my assistant at our office line (415) 555-0199 or write to my direct line admin@thunderlizard.agency. Our office is at 44 Madison Ave, NYC — the door’s open for coffee.”',
    badExample: '“Thanks for the email! We can Zoom. I\'m a small shop but we\'re dedicated. My cell is 415-555-4587 if that’s easier.”',
  },
  {
    title: "Quantify Transformation, Not Improvement",
    scope: "global",
    surface: "PROPOSAL" as const,
    sourceRef: "DotCom Secrets by Russell Brunson — Pages 88-88",
    instruction: "In proposals, state the before-and-after outcome with specific numbers and a specific deadline; remove all adjectives like \'better\', \'quality\', or \'improved\' — they lose deals.",
    goodExample: '“By day 60, your quoting time drops from 4 hours per bid to 30 minutes — freeing 3.5 hours of engineering time per bid, which will crank your bid capacity from 20/month to 30/month without adding a headcount.”',
    badExample: '“Our system greatly improves operational efficiency and reduces turnaround times, significantly boosting your quoting output.”',
  },
  {
    title: "Nurture with Value, Not Pitches",
    scope: "global",
    surface: "EMAIL" as const,
    sourceRef: "DotCom Secrets by Russell Brunson — Pages 45-49",
    instruction: "Every follow-up email after a lead goes quiet must consist of 80% educational value (tutorial, insight, or template) and 20% response bait asking for feedback or relevance — never produce a standalone \'checking in\' email again.",
    goodExample: '“Since we spoke, I saw your LinkedIn that you hired a Demand Gen lead. Here\'s the template we give every client for the first 30-day sprint — steal it. By the way — has the new GM changed the metrics you report into leadership?”',
    badExample: '“Haven\'t heard from you in a few weeks. Just wanted to touch base and see if you had any questions or moving pieces I can help with.”',
  },
  {
    title: "Learn from the Marginal Few",
    scope: "global",
    surface: "REPLY" as const,
    sourceRef: "DotCom Secrets by Russell Brunson — Pages 19-20, 61-62",
    instruction: "At the end of each quarter, ask a simple, non-leading question to both a profitable and a lost/quiet client: \'What changed in your situation that made us relevant/ irrelevant now?\' Use the verbatim answer in new copy and positioning.",
    goodExample: '“Good to connect. Last time you mentioned being overrun with off-boarding requests from your M&A deals. Now that you\'ve secured the acquisition—what\'s the #1 friction in onboarding those data assets into Salesforce?”',
    badExample: '“Is the timing any better now? Has anything changed? We still have that Q3 slot open. Hope the acquisition went well, by the way!”',
  },

  // ── 1-PAGE MARKETING PLAN (Allan Dib) ──────────────────────────────────────
  {
    title: "Lead With Profitable Outcome",
    scope: "sales",
    surface: "EMAIL" as const,
    sourceRef: "Allan Dib’s The 1-Page Marketing Plan — Lessons 1, 8, 11, 29",
    instruction: "When crafting any B2B sales communication, open with a specific, credible ROI or cash-flow outcome rather than a mission, product, or relationship statement.",
    goodExample: '“Most agencies we speak with are leaving $50k+/year on the table from silent churn. Our audit typically surfaces exactly where, and the fix pays for itself 3x within 60 days.”',
    badExample: '“We\'re a passionate team that loves helping brands tell their story and connect with customers on a deeper level.”',
  },
  {
    title: "Open With Existing Acute Pain",
    scope: "sales",
    surface: "EMAIL" as const,
    sourceRef: "Allan Dib’s The 1-Page Marketing Plan — Lessons 4, 32, 109",
    instruction: "When writing outreach, identify the prospect's most acute, currently-felt pain point and make it the first sentence, before mentioning your product.",
    goodExample: '“Your quote-to-close rate is likely under 20%, and I bet you have no idea why. That\'s costing you six figures in lost revenue every quarter.”',
    badExample: '“I wanted to reach out today because our platform helps companies increase efficiency and save time, which is critical for staying competitive in today\'s market.”',
  },
  {
    title: "Use Pain Jargon To Resonate",
    scope: "sales",
    surface: "EMAIL" as const,
    sourceRef: "Allan Dib’s The 1-Page Marketing Plan — Lessons 24, 35",
    instruction: "When writing copy for a niche, use their specific industry jargon and pain vocabulary to prove you understand their world, not generic business language.",
    goodExample: '“Struggling with OSHA 300 log injuries that are eating your EMR rating and spiking your workers\' comp premiums? We fix that for self-insured manufacturers over 100 employees.”',
    badExample: '“We help companies improve safety, reduce workplace incidents, and build a better culture for all employees.”',
  },
  {
    title: "Clarity Beats Cleverness Every Time",
    scope: "sales",
    surface: "EMAIL" as const,
    sourceRef: "Allan Dib’s The 1-Page Marketing Plan — Lesson 40",
    instruction: "When naming an offer, writing a headline, or creating a subject line, always choose plain, unambiguous language over clever or witty phrasing.",
    goodExample: '“Subject: The 3-Page Report That Has Helped 7 Agencies Double Their Client Retention in 6 Months”',
    badExample: '“Subject: The Purple Zebra\'s Guide to Navigating the Cross-Channel Murky Waters”',
  },
  {
    title: "Name The Elephant In The Room",
    scope: "sales",
    surface: "PROPOSAL" as const,
    sourceRef: "Allan Dib’s The 1-Page Marketing Plan — Lessons 38, 74",
    instruction: "In any pitch or proposal, proactively acknowledge and address the biggest perceived risk or objection (price, implementation, trust) before the prospect raises it.",
    goodExample: '“You\'re likely thinking, \'This is going to be a huge lift and we\'ll see results in 18 months.\' We get it. That\'s why we split the project into 3 phases, with phase 1 delivering a tangible win in just 30 days and costing less than your current spend on ineffective ads.”',
    badExample: '“We are confident our enterprise solution will drive results for your organization, and we\'re excited to get started on this transformation journey together.”',
  },
  {
    title: "Stack Bonuses, Never Discount Price",
    scope: "sales",
    surface: "PROPOSAL" as const,
    sourceRef: "Allan Dib’s The 1-Page Marketing Plan — Lesson 34",
    instruction: "When you need to increase conversion, add contextual, high-perceived-value bonuses to the deal rather than cutting your price, which devalues your core offer.",
    goodExample: '“The retainer price stays the same. However, if you sign by Friday, I\'ll include our \'Sales Playbook for Your Exact Niche\' (valued at $1,500) and a quarterly strategy session to implement it, with no extra charge.”',
    badExample: '“We really want to work with you, so let\'s do a 10% discount on the first quarter. Can we close on this?”',
  },
  {
    title: "Push Immediate Specific Guarantee",
    scope: "sales",
    surface: "PROPOSAL" as const,
    sourceRef: "Allan Dib’s The 1-Page Marketing Plan — Lesson 74",
    instruction: "When a prospect hesitates, replace a vague promise with a specific, measurable guarantee that names their exact fear and states a concrete penalty or refund if unmet.",
    goodExample: '“If we don\'t increase your SQL volume by 30% in the first 90 days, we\'ll work for free until we do, or you can cancel and pay nothing.”',
    badExample: '“We are 100% committed to client success and are confident in our ability to deliver high-quality work that drives significant business results.”',
  },
  {
    title: "Offer Two-Tiered Value Ladder",
    scope: "sales",
    surface: "PROPOSAL" as const,
    sourceRef: "Allan Dib’s The 1-Page Marketing Plan — Lesson 75",
    instruction: "When presenting pricing, always offer exactly two options: a Standard and a Premium tier, with the premium priced at least 30% higher but positioned as at least 2x the value.",
    goodExample: '“Option 1: Standard Growth ($5k/mo) gets you the core engagement. Option 2: Accelerator ($6.5k/mo) includes everything in Standard plus our dedicated CRO specialist to optimize your funnel weekly—that alone often doubles the return you see.”',
    badExample: '“Our pricing is flexible and we can do a custom package based on your needs. What\'s your budget?”',
  },
  {
    title: "Frame Referrals As Valuable Gift",
    scope: "sales",
    surface: "REPLY" as const,
    sourceRef: "Allan Dib’s The 1-Page Marketing Plan — Lessons 89, 94",
    instruction: "When asking a happy client for a referral, frame the request as giving them a valuable asset to share, not as doing you a favor.",
    goodExample: '“I\'ve just sent you a copy of our \'Client Acquisition Checklist for Manufacturers\' to share with your supplier network. It\'s a great way to give your contacts a quick win, and if they\'d like a free analysis, they can book time directly on my calendar.”',
    badExample: '“Hey John, since you\'re happy, do you know anyone else who might need our services? We\'re looking to grow our client roster and we\'d appreciate an intro.”',
  },
  {
    title: "Educate Before Hard Selling",
    scope: "sales",
    surface: "EMAIL" as const,
    sourceRef: "Allan Dib’s The 1-Page Marketing Plan — Lessons 59, 68, 72",
    instruction: "After a prospect shows initial interest, your next message must educate with valuable content and avoid any hard sales ask or pitch.",
    goodExample: '“Hi [Name], As promised, here is the link to the \'3-Step Data Migration Checklist.\' It\'ll walk you through avoiding the top 3 pitfalls we see. No call required. Just wanted to get this in your hands.”',
    badExample: '“Hi [Name], Since you downloaded the checklist, I assume you\'re ready to talk. Are you free for a 30-minute call tomorrow at 2pm to see how we can help?”',
  },
  {
    title: "Resolve Issues Before Referral Request",
    scope: "sales",
    surface: "REPLY" as const,
    sourceRef: "Allan Dib’s The 1-Page Marketing Plan — Lesson 91",
    instruction: "When a customer reports a problem, fix it and confirm their satisfaction before making any referral request.",
    goodExample: '“This is resolved, and the extra data has been uploaded. Please verify that everything is now correct on your end. Once you\'ve confirmed, I\'d love to discuss how we can help a few others in your network avoid this same issue.”',
    badExample: '“Glad we fixed that issue. By the way, we\'re looking for new clients, so any referrals would be great!”',
  },
  {
    title: "Sell Wants Not Just Needs",
    scope: "sales",
    surface: "PROPOSAL" as const,
    sourceRef: "Allan Dib’s The 1-Page Marketing Plan — Lesson 77",
    instruction: "When describing your offer, lead with the emotional outcome the prospect wants, then connect it to the functional need it serves.",
    goodExample: '“Would you like to finally feel in control of your weekend, instead of dreading a Monday morning inbox overflow? That\'s what our 4-day work week \'Automation Sprint\' gives you—it reclaims your personal time by automating the busywork.”',
    badExample: '“Our automation software streamlines workflow, increases efficiency, and reduces operational costs. It\'s the most robust solution on the market.”',
  },
  {
    title: "Personalize Targeting For Recognition",
    scope: "sales",
    surface: "EMAIL" as const,
    sourceRef: "Allan Dib’s The 1-Page Marketing Plan — Lessons 25, 26",
    instruction: "When crafting any sales message, explicitly state who it's for and who it's not for, making the prospect feel you're speaking only to them.",
    goodExample: '“This offer is for B2B SaaS founders who have closed 20+ customers but feel like they\'re drowning in one-off service requests. It\'s not for teams larger than 50 people.”',
    badExample: '“Our solution helps businesses of all sizes streamline their customer service operations and improve satisfaction across the board.”',
  },
  {
    title: "Ask Targeted Qualifying Question",
    scope: "sales",
    surface: "REPLY" as const,
    sourceRef: "Allan Dib’s The 1-Page Marketing Plan — Lesson 70",
    instruction: "When a prospect asks for a quote or collateral, pause and ask one focused question about their current situation or trigger event before sending anything.",
    goodExample: '“I\'d be glad to send you details on our solutions. Quick question: are you exploring this because you\'re looking to replace an existing platform, or is this for a new initiative?”',
    badExample: '“Absolutely, I\'ll email you over our full pricing guide and product sheet right away!”',
  },
  {
    title: "Pivot From Commodity To Category",
    scope: "sales",
    surface: "REPLY" as const,
    sourceRef: "Allan Dib’s The 1-Page Marketing Plan — Lesson 28",
    instruction: "When the prospect tries to compare your price to a direct competitor, reframe the conversation to a different category to avoid a price war.",
    goodExample: '“I\'m not really in the \'outsourced marketing\' category that you\'re price-comparing. Think of a CFO bringing in a tax strategist, versus just getting your taxes done. I\'m the strategist, and my output is a growth plan, not just content. The difference is $1k vs. $10k, but the ROI is 10x.”',
    badExample: '“Yes we are a bit more expensive than others, but you get a lot more for your money with our higher level of service and attention.”',
  },
  {
    title: "Value Time Over Money",
    scope: "sales",
    surface: "PROPOSAL" as const,
    sourceRef: "Allan Dib’s The 1-Page Marketing Plan — Lesson 103",
    instruction: "In proposals and pricing discussions, always justify cost based on the specific business value saved or earned, not the hours spent.",
    goodExample: '“This project is not just a website; it\'s expected to generate 25 new enquiries a month. At your close rate, that\'s $50k in new MRR—making this engagement pay for itself in the first 2 weeks.”',
    badExample: '“The project costs $15k because we estimate our team will spend roughly 200 hours on design, development, and project management.”',
  },
  {
    title: "Recommend Paid Shortcuts",
    scope: "sales",
    surface: "EMAIL" as const,
    sourceRef: "Allan Dib’s The 1-Page Marketing Plan — Lesson 9",
    instruction: "In sales emails and proposals, actively recommend a paid option, tool, or service that saves the prospect more time or money than it costs, framing it as an investment.",
    goodExample: '“If this sounds like a lot, I\'d strongly suggest using a tool like [Tool Name] to automate this report. It costs $50/month but it will save your team 10 hours a month. We can help you set it up if you\'d like.”',
    badExample: '“You can of course do this internally, as it\'s mostly just pulling together spreadsheets and data. It\'s straightforward but does take some time.”',
  },
  {
    title: "Incite Core Emotional Hot Button",
    scope: "sales",
    surface: "EMAIL" as const,
    sourceRef: "Allan Dib’s The 1-Page Marketing Plan — Lesson 37",
    instruction: "Before sending any headline, subject line, or email, ensure it triggers at least one of these five emotions: fear, love, greed, guilt, or pride.",
    goodExample: '“Subject: [Name], are you suffering from high CAC and losing to cheaper competitors?”',
    badExample: '“Subject: February Client Update and Quarterly Business Review.”',
  },
  {
    title: "Switch With A Tangible Follow-Up",
    scope: "sales",
    surface: "EMAIL" as const,
    sourceRef: "Allan Dib’s The 1-Page Marketing Plan — Lesson 63",
    instruction: "For high-value prospects that are ignoring digital outreach, switch channels by sending a physical, attention-grabbing item directly related to their business.",
    goodExample: '“After 5 unanswered emails, mail a personalized, small gift (like a custom branded USB loaded with your case studies) to their office with a \'Happy Q3\' note.”',
    badExample: '“Send a 12th follow-up email starting with \'Hey, just checking in again to see if you got my last email. Let me know if you\'re interested.\'”',
  },
  {
    title: "Track ROI Not Vanity Metrics",
    scope: "sales",
    surface: "ADVISOR" as const,
    sourceRef: "Allan Dib’s The 1-Page Marketing Plan — Lesson 47",
    instruction: "When discussing campaign performance, shift the conversation to actual profit (ROI) and away from open rates and click-through rates.",
    goodExample: '“I know the opens were average, but I ran the numbers and the CAC from this campaign was $450 vs. an LTV of $4,000. That\'s a 9x return, so we should triple the budget.”',
    badExample: '“The open rate was only 20%, but the click-through was good. Let\'s keep testing different subject lines to see if we can improve things.”',
  },
  {
    title: "Diversify To Five Lead Sources",
    scope: "sales",
    surface: "ADVISOR" as const,
    sourceRef: "Allan Dib’s The 1-Page Marketing Plan — Lesson 55",
    instruction: "When advising on marketing strategy, instruct the client to build at least five distinct lead sources so the business doesn't fail if one channel dries up.",
    goodExample: '“Google Ads is great, but you\'re currently 90% reliant on it. Over the next quarter, we\'ll build 4 other channels: SEO, a referral partner network, a LinkedIn outreach campaign, and a partnership with a complementary, non-competing firm.”',
    badExample: '“Let\'s put 90% of your marketing budget into this one winning Facebook ad campaign and maximize our return before it gets stale.”',
  },
  {
    title: "Ask For The Sale Directly",
    scope: "sales",
    surface: "EMAIL" as const,
    sourceRef: "Allan Dib’s The 1-Page Marketing Plan — Lesson 3",
    instruction: "Every sales communication must end with a single, concrete, low-friction call-to-action that asks for the next step, like a call, meeting, or reply.",
    goodExample: '“If this makes sense, reply \'yes\' and I\'ll send you an invite for a 15-minute scoping call on Tuesday at 9:30 or Wednesday at 3pm. Which is better?”',
    badExample: '“Let me know what you think and we can maybe explore if there\'s a way to work together in the future.”',
  },
  {
    title: "Speak Human, Not Corporate",
    scope: "sales",
    surface: "ALL" as const,
    sourceRef: "Allan Dib’s The 1-Page Marketing Plan — Lessons 36, 49",
    instruction: "Write and speak in a natural, conversational tone that sounds like a human talking to a single person, not corporate jargon.",
    goodExample: '“Hey, I saw you\'re drowning in manual lead entry. That\'s a real pain. We\'ve helped a few Roofers switch to our automated system and it just saved them 5 hours a week. Interested?”',
    badExample: '“Our comprehensive CRM solution is designed to synergize your sales and operational workflows, driving an enterprise-grade digital transformation.”',
  },
  {
    title: "Support Claims With Proof",
    scope: "sales",
    surface: "PROPOSAL" as const,
    sourceRef: "Allan Dib’s The 1-Page Marketing Plan — Lesson 110",
    instruction: "When making a big claim, immediately follow it with a specific, credible number, case study, or well-known client as proof.",
    goodExample: '“SaaS companies in your niche typically see a 30% lift in contract value within 3 months of adopting this framework. We just did this for [Mutual Connection] and they closed a $50k annual deal this week.”',
    badExample: '“Our clients see massive growth once they implement our strategies and processes. Our team has a proven track record of success across a wide variety of industries.”',
  },
]

async function sync() {
  console.log(`\n======================================================`)
  console.log(`🧠 Syncing ${MASTER_RULES.length} Direct-Response AI Training Rules`)
  console.log(`======================================================`)

  const existingRules = await prisma.aiTrainingRule.findMany({
    where: { userId: null },
  })

  const existingMap = new Map(existingRules.map(r => [r.title.toLowerCase().trim(), r]))

  let createdCount = 0
  let updatedCount = 0

  const batchSize = 10
  for (let i = 0; i < MASTER_RULES.length; i += batchSize) {
    const chunk = MASTER_RULES.slice(i, i + batchSize)
    await Promise.all(
      chunk.map(async r => {
        const existing = existingMap.get(r.title.toLowerCase().trim())
        if (existing) {
          await prisma.aiTrainingRule.update({
            where: { id: existing.id },
            data: {
              scope: r.scope,
              surface: r.surface,
              instruction: r.instruction,
              goodExample: r.goodExample,
              badExample: r.badExample,
              source: "document",
              sourceRef: r.sourceRef,
              enabled: true,
            },
          })
          updatedCount++
        } else {
          await prisma.aiTrainingRule.create({
            data: {
              title: r.title,
              scope: r.scope,
              surface: r.surface,
              instruction: r.instruction,
              goodExample: r.goodExample,
              badExample: r.badExample,
              source: "document",
              sourceRef: r.sourceRef,
              enabled: true,
              userId: null,
            },
          })
          createdCount++
        }
      })
    )
  }

  invalidateTrainingCache()

  console.log(`\n✅ Directives Sync Complete!`)
  console.log(`- Created: ${createdCount}`)
  console.log(`- Updated: ${updatedCount}`)
  console.log(`- Total Master Rules: ${MASTER_RULES.length}`)

  console.log(`\n--- Verification of Injected Training Blocks ---`)
  for (const surface of ["EMAIL", "REPLY", "PROPOSAL", "ADVISOR"] as const) {
    const block = await getTrainingBlock(surface, "sales", null)
    console.log(`\n[${surface} BLOCK PREVIEW] (Length: ${block.length} chars)`)
    console.log(block.slice(0, 350) + "...\n")
  }
  console.log(`======================================================\n`)
  process.exit(0)
}

sync().catch(err => {
  console.error("Sync failed:", err)
  process.exit(1)
})
